export const yachts = [
  {
    name: "Ариель",
    price: 7000,
    imageSrc: '/ariel.jpg',
    imageDescriptionOne: '/ariel1.jpg',
    imageDescriptionTwo: '/ariel2.jpg',
    imageDescriptionThree: '/ariel3.jpg',
    imageDescriptionFour: '/ariel4.jpg',
    description: {
      "Количество туалетов": 1,
      "Количество душевых": 1,
      "Количество кают": 2,
      "Количество спальных мест": 6,
      "Модель": "Meridian 341",
      "Длина, м": 11,
      "Ширина, м": 3.7,
      "Страна производитель": "США",
      "Год постройки": 2008,
      "Количество двигателей": 2,
      "Высота борта, м": 1.6,
      "Мощность двигателя, л/с": 330,
      "Максимальная скорость, км/ч": 72,
      "Вмещает": "до 11 гостей",
    },
  },
  {
    name: "Марсель",
    price: 15000,
    imageSrc: '/marsel.jpg',
    imageDescriptionOne: '/marsel1.jpg',
    imageDescriptionTwo: '/marsel2.jpg',
    imageDescriptionThree: '/marsel3.jpg',
    imageDescriptionFour: '/marsel4.jpg',
    description: {
      "Количество туалетов": 1,
      "Количество душевых": 2,
      "Количество кают": 2,
      "Количество спальных мест": 6,
      "Модель": "Meridian 39",
      "Длина, м": 13.5,
      "Ширина, м": 3.5,
      "Страна производитель": "США",
      "Год постройки": 2006,
      "Количество двигателей": 2,
      "Высота борта, м": 2.5,
      "Мощность двигателя, л/с": 350,
      "Максимальная скорость, км/ч": 56,
      "Объем бака пресной воды": "400 л",
      "Объем топливного бака": "1000 л",
    },
  },
  {
    name: "Азимут 42",
    price: 17000,
    imageSrc: '/azimut.jpg',
    imageDescriptionOne: '/azimut1.jpg',
    imageDescriptionTwo: '/azimut2.jpg',
    imageDescriptionThree: '/azimut3.jpg',
    imageDescriptionFour: '/azimut4.jpg',
    description: {
      "Количество туалетов": 1,
      "Количество душевых": 1,
      "Количество кают": 2,
      "Количество спальных мест": 6,
      "Модель": "Meridian 341",
      "Длина, м": 11,
      "Ширина, м": 3.7,
      "Страна производитель": "США",
      "Год постройки": 2008,
      "Количество двигателей": 2,
      "Высота борта, м": 1.6,
      "Мощность двигателя, л/с": 330,
      "Максимальная скорость, км/ч": 72,
      "Вмещает": "до 11 гостей",
    },
  },
  {
    name: "Принцесса 56",
    price: 25000,
    imageSrc: '/princes.jpg',
    imageDescriptionOne: '/princes1.jpg',
    imageDescriptionTwo: '/princes5.jpg',
    imageDescriptionThree: '/princes3.jpg',
    imageDescriptionFour: '/princes4.jpg',
    description: {
      "Количество туалетов": 1,
      "Количество душевых": 1,
      "Количество кают": 2,
      "Количество спальных мест": 6,
      "Модель": "Meridian 341",
      "Длина, м": 11,
      "Ширина, м": 3.7,
      "Страна производитель": "США",
      "Год постройки": 2008,
      "Количество двигателей": 2,
      "Высота борта, м": 1.6,
      "Мощность двигателя, л/с": 330,
      "Максимальная скорость, км/ч": 72,
      "Вмещает": "до 11 гостей",
    },
  },
  {
    name: "Моторная яхта Мира",
    price: 10000,
    imageSrc: '/mira.jpg',
    imageDescriptionOne: '/mira1.jpg',
    imageDescriptionTwo: '/mira2.jpg',
    imageDescriptionThree: '/mira3.jpg',
    imageDescriptionFour: '/mira4.jpg',
    description: {
      "Количество туалетов": 1,
      "Количество душевых": 1,
      "Количество кают": 2,
      "Количество спальных мест": 6,
      "Модель": "Meridian 341",
      "Длина, м": 11,
      "Ширина, м": 3.7,
      "Страна производитель": "США",
      "Год постройки": 2008,
      "Количество двигателей": 2,
      "Высота борта, м": 1.6,
      "Мощность двигателя, л/с": 330,
      "Максимальная скорость, км/ч": 72,
      "Вмещает": "до 11 гостей",
    },
  },
  {
    name: "Катер Белини",
    price: 8000,
    imageSrc: '/belini.jpg',
    imageDescriptionOne: '/belini1.jpg',
    imageDescriptionTwo: '/belini2.jpg',
    imageDescriptionThree: '/belini3.jpg',
    imageDescriptionFour: '/belini4.jpg',
    description: {
      "Количество туалетов": 1,
      "Количество душевых": 1,
      "Количество кают": 2,
      "Количество спальных мест": 5,
      "Модель": "Airon Marine 345",
      "Длина, м": 11,
      "Ширина, м": 3.5,
      "Страна производитель": "Италия",
      "Год постройки": 2010,
      "Количество двигателей": 2,
      "Высота борта, м": 1,
      "Мощность двигателя, л/с": "2 × 300",
      "Максимальная скорость, км/ч": 75,
      "Вмещает": "до 10 гостей",
    },
  },
  {
    name: "Родман 64",
    price: 55000,
    imageSrc: '/rodman.jpg',
    imageDescriptionOne: '/rodman1.jpg',
    imageDescriptionTwo: '/rodman2.jpg',
    imageDescriptionThree: '/rodman3.jpg',
    imageDescriptionFour: '/rodman4.jpg',
    description: {
      "Бренд": "RODMAN",
      "Модель": "RODMAN 64 FLY",
      "Год выпуска": 2005,
      "Длина": "19,00 м",
      "Ширина": "5,00 м",
      "Осадка":" 1,00 м",
      "Двигатели": "2 × 1050 л.с.",
      "Вместимость": 10,
      "Количество кают": 3,
      "Скорость круизная": "25 уз",
      "Объем бака для воды": "800 л",
      "Объем топливного бака": "4200 л",
    },
  },
  {
    name: "Катер Монтерей",
    price: 7000,
    imageSrc: '/monterey.jpg',
    imageDescriptionOne: '/monterey.jpg',
    imageDescriptionTwo: '/monterey1.jpg',
    imageDescriptionThree: '/monterey3.jpg',
    imageDescriptionFour: '/monterey4.jpg',
    description: {
      "Количество туалетов": 1,
      "Количество душевых": 1,
      "Количество кают": 2,
      "Количество спальных мест": 6,
      "Модель": "Meridian 341",
      "Длина, м": 11,
      "Ширина, м": 3.7,
      "Страна производитель": "США",
      "Год постройки": 2008,
      "Количество двигателей": 2,
      "Высота борта, м": 1.6,
      "Мощность двигателя, л/с": 330,
      "Максимальная скорость, км/ч": 72,
      "Вмещает": "до 11 гостей",
    },
  },
  {
    name: "Катер Флорида",
    price: 6500,
    imageSrc: '/florida.jpg',
    imageDescriptionOne: '/florida1.jpg',
    imageDescriptionTwo: '/florida2.jpg',
    imageDescriptionThree: '/florida3.jpg',
    imageDescriptionFour: '/florida4.jpg',
    description: {
      "Количество туалетов": 1,
      "Количество душевых": 1,
      "Количество кают": 2,
      "Количество спальных мест": 6,
      "Модель": "Meridian 341",
      "Длина, м": 11,
      "Ширина, м": 3.7,
      "Страна производитель": "США",
      "Год постройки": 2008,
      "Количество двигателей": 2,
      "Высота борта, м": 1.6,
      "Мощность двигателя, л/с": 330,
      "Максимальная скорость, км/ч": 72,
      "Вмещает": "до 11 гостей",
    },
  },
  {
    name: "Катер Принцесса Фиона",
    price: 6000,
    imageSrc: '/princes2.jpg',
    imageDescriptionOne: '/princes6.jpg',
    imageDescriptionTwo: '/princes7.jpg',
    imageDescriptionThree: '/princes8.jpg',
    imageDescriptionFour: '/princes9.jpg',
    description: {
      "Количество туалетов": 1,
      "Количество душевых": 2,
      "Количество кают": 1,
      "Количество спальных мест": 2,
      "Модель": "Байлайнер 2655",
      "Длина, м": 11.8,
      "Ширина, м": 3.8,
      "Объем бака пресной воды, л": "200 л",
      "Объем топливного бака, л": "260 л",
      "Страна производитель": "США",
      "Год постройки": 2002,
      "Количество двигателей": 1,
      "Высота борта, м": 1.5,
      "Мощность двигателя, л/с": 200,
      "Максимальная скорость, км/ч": "20 узлов",
      "Вмещает": "до 6 гостей",
    },
  },
  {
    name: "Катер Андора",
    price: 8000,
    imageSrc: '/andora.jpg',
    imageDescriptionOne: '/andora1.jpg',
    imageDescriptionTwo: '/andora2.jpg',
    imageDescriptionThree: '/andora3.jpg',
    imageDescriptionFour: '/andora4.jpg',
    description: {
      "Количество туалетов": 1,
      "Количество душевых": 1,
      "Количество кают": 2,
      "Количество спальных мест": 6,
      "Модель": "Meridian 341",
      "Длина, м": 11,
      "Ширина, м": 3.7,
      "Страна производитель": "США",
      "Год постройки": 2008,
      "Количество двигателей": 2,
      "Высота борта, м": 1.6,
      "Мощность двигателя, л/с": 330,
      "Максимальная скорость, км/ч": 72,
      "Вмещает": "до 11 гостей",
    },
  },
  {
    name: "Катер Анастасия",
    price: 5500,
    imageSrc: '/nastya.jpg',
    imageDescriptionOne: '/nastya.jpg',
    imageDescriptionTwo: '/nastya1.jpg',
    imageDescriptionThree: '/nastya2.jpg',
    imageDescriptionFour: '/nastya3.jpg',
    description: {
      "Количество туалетов": 1,
      "Количество душевых": 1,
      "Количество кают": 1,
      "Количество спальных мест": 2,
      "Модель": "Скайлайн 242 CR",
      "Длина, м": 7.3,
      "Ширина, м": 2.6,
      "Страна производитель": "США",
      "Год постройки": 2000,
      "Количество двигателей": 1,
      "Объем бака пресной воды, л": "100 л",
      "Объем топливного бака, л": "270 л",
      "Высота борта, м": 1.5,
      "Мощность двигателя, л/с": 270,
      "Максимальная скорость, км/ч": "20 узлов",
      "Вмещает": "до 11 гостей",
    },
  },
  {
    name: "Катамаран Апрель",
    price: 15000,
    imageSrc: '/aprel.jpg',
    imageDescriptionOne: '/aprel1.jpg',
    imageDescriptionTwo: '/aprel2.jpg',
    imageDescriptionThree: '/aprel3.jpg',
    imageDescriptionFour: '/aprel4.jpg',
    description: {
      "Длина": "12 м",
      "Ширина": "6.4 м",
      "Скорость": "7-10 узлов",
      "Вместимость": "10 человек",
      "Кают": "3 шт",
    },
  },
  {
    name: "Спортивная парусная яхта Индиго",
    price: 7000,
    imageSrc: '/indigo.jpg',
    imageDescriptionOne: '/indigo1.jpg',
    imageDescriptionTwo: '/indigo2.jpg',
    imageDescriptionThree: '/indigo3.jpg',
    imageDescriptionFour: '/indigo4.jpg',
    description: {
      "Количество туалетов": 1,
      "Количество душевых": 1,
      "Количество кают": "2 + кают компания",
      "Модель": "E 3",
      "Длина, м": 10,
      "Ширина, м": 3.5,
      "Страна производитель": "Словения",
      "Год постройки": 2016,
      "Количество двигателей": 1,
      "Высота борта, м": 1.6,
      "Мощность двигателя, л/с": 45,
      "Максимальная скорость, км/ч": 35,
      "Вмещает": "до 7 гостей",
    },
  },
  {
    name: "Яхта премиум класса. Санта Люция",
    price: 55000,
    imageSrc: '/santa.jpg',
    imageDescriptionOne: '/santa1.jpg',
    imageDescriptionTwo: '/santa2.jpg',
    imageDescriptionThree: '/santa3.jpg',
    imageDescriptionFour: '/santa4.jpg',
    description: {
      "Количество туалетов": 1,
      "Количество душевых": 1,
      "Количество кают": 2,
      "Количество спальных мест": 6,
      "Модель": "Meridian 341",
      "Длина, м": 11,
      "Ширина, м": 3.7,
      "Страна производитель": "США",
      "Год постройки": 2008,
      "Количество двигателей": 2,
      "Высота борта, м": 1.6,
      "Мощность двигателя, л/с": 330,
      "Максимальная скорость, км/ч": 72,
      "Вмещает": "до 11 гостей",
    },
  },
  {
    name: "Сан Сикер",
    price: 55000,
    imageSrc: '/san.jpg',
    imageDescriptionOne: '/san.jpg',
    imageDescriptionTwo: '/san.jpg',
    imageDescriptionThree: '/san.jpg',
    imageDescriptionFour: '/san.jpg',
    description: {
      "Количество туалетов": 1,
      "Количество душевых": 1,
      "Количество кают": 2,
      "Количество спальных мест": 6,
      "Модель": "Meridian 341",
      "Длина, м": 11,
      "Ширина, м": 3.7,
      "Страна производитель": "США",
      "Год постройки": 2008,
      "Количество двигателей": 2,
      "Высота борта, м": 1.6,
      "Мощность двигателя, л/с": 330,
      "Максимальная скорость, км/ч": 72,
      "Вмещает": "до 11 гостей",
    },
  },
  {
    name: "Яхта Багратион",
    price: 55000,
    imageSrc: '/bagration.jpg',
    imageDescriptionOne: '/bagration1.jpg',
    imageDescriptionTwo: '/bagration2.jpg',
    imageDescriptionThree: '/bagration3.jpg',
    imageDescriptionFour: '/bagration4.jpg',
    description: {
      "Количество туалетов": 1,
      "Количество душевых": 1,
      "Количество кают": 2,
      "Количество спальных мест": 6,
      "Модель": "Meridian 341",
      "Длина, м": 11,
      "Ширина, м": 3.7,
      "Страна производитель": "США",
      "Год постройки": 2008,
      "Количество двигателей": 2,
      "Высота борта, м": 1.6,
      "Мощность двигателя, л/с": 330,
      "Максимальная скорость, км/ч": 72,
      "Вмещает": "до 11 гостей",
    },
  },
  {
    name: "Итальянский катер Пеликан",
    price: 9000,
    imageSrc: '/pelikan.jpg',
    imageDescriptionOne: '/pelikan1.jpg',
    imageDescriptionTwo: '/pelikan2.jpg',
    imageDescriptionThree: '/pelikan3.jpg',
    imageDescriptionFour: '/pelikan4.jpg',
    description: {
      "Количество туалетов": 1,
      "Количество душевых": 1,
      "Количество кают": 2,
      "Количество спальных мест": 6,
      "Модель": "Meridian 341",
      "Длина, м": 11,
      "Ширина, м": 3.7,
      "Страна производитель": "США",
      "Год постройки": 2008,
      "Количество двигателей": 2,
      "Высота борта, м": 1.6,
      "Мощность двигателя, л/с": 330,
      "Максимальная скорость, км/ч": 72,
      "Вмещает": "до 11 гостей",
    },
  },
];
